### ISSUE TITLE
Question: How to customize [markup.highlight] in front matter?

### ISSUE THREAD

**Issue by prosoitos** [dzello/reveal-hugo#107]
Thanks once more for this theme 🙂 I use it for all my presentations 🙂 

One thing that I never figured out is how to have different chroma styles for different presentations within the same repo (i.e. how to set [markup.highlight] in the front matter instead of in config.toml).

This is what I have in my config.toml:

```toml
[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.highlight]
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
```

It works great. But I don't know how to use a different chroma style for some presentations.

The workaround I have used so far is to have different Git branches or different repos for the presentations that use a different style. But it would make my workflow so much simpler not to have to do that and to simply be able to set the style in the front matter of each _index.md file!

Thanks!
