### ISSUE TITLE
plugins usage and inclusion redesign

### ISSUE THREAD

**Issue by davidovich** [dzello/reveal-hugo#132]
Problem statement
------------------

At the moment, plugins can be included in reveal-hugo with these 4 steps:

* include the plugin in the site tree
* add a [params.]reveal_hugo.plugins array to the front matter (or config.toml)
* create a head.html layout
* add appropriate css to that new file.

This is ok, but some [users](#96) seem to feel this is unwieldy.

Also, in the new reveal-js upgrade, a new registration mechanism is introduced which needs the Plugin object to crystalize plugin registration. @chrisreddington voiced [seeking guidance](https://github.com/dzello/reveal-hugo/pull/115#discussion_r814929622) on this fact. 

Proposition
-----------

I believe that by enhancing the plugins array, we can prepare for a better upgrade route and support legacy. 

I propose to make the plugins slice a slice of objects with these fields:

```toml
[[plugins]]
name = "RevealNotes" # used to give the plugin the name used for registration
source =  "reveal-js/plugin/notes/notes.js" # "relative/path/to/plugin.js"
css = "relative/path/to/plugin.css"
local = [true|false] # override any cdn prefix that would be configured
```

Consequences
---------------

By packing more information, reveal-hugo is also able to do more:

* It can remove the need for the user to add a partial layout just for specifying css (the build step can do that for the user)
* We have enough information to fix questioning raised in #115, as we can register plugins with the now required plugin name
* Cdn based plugins can be consumed (there is currently a limitation in the docs about this)
* Default plugins and user plugins receive the same treatment and are registered in the same way.
* Upgrading to reveal 4 is facilitated

We should worry about current implementations that specify plugins by path only, and support those for backward compatibility (we can infer that the current object is a string). But the name will be needed for reveal 4.0+ support in the future.

@dzello WDYT?
