### ISSUE TITLE
Don't populate disabled plugins in the generated tree

### ISSUE THREAD

**Issue by chandlerc** [dzello/reveal-hugo#151]
Currently, even when I disable the default plugins and enable a selective subset, the generated tree includes all the files for the plugins, for example all the CSS files for highlight.js that I don't actually use.

It'd be nice if there was a way to suppress this.

**Comment by chandlerc** [comment]
I didn't really think it would work, but adding a section for `[[module.mounts]]` like:
```toml
[[mounts]]
  source = '/dev/null'
  target = 'static/highlight-js'
```

Seems to do what I want. This does seem a bit of a hack though, but it at least lets me zap the directories not needed from my deployment.
