### ISSUE TITLE
Organizing content in subfolders breaks my custom theme

### ISSUE THREAD

**Issue by ccamara** [dzello/reveal-hugo#39]
I would like to use a single reveal-hugo instance to put all my slides. Therefore, I would like to group slides from my job1, job2, association and personal slides. I though of creating a structure like this:

```
content
├── job1
│   ├── presentation1
│   │    ├── page.md
│   │    └── _index.md
│   └── presentation2
│         └── _index.md
└── personal
    ├── presentation2
    │    └── _index.md
    └── presentation2
          └── _index.md
```

While IMHO this makes much sense because I can apply different partials per purpose, I noticed that my custom scss theme was not applying for content in `content/job1/presentation1/page.md`. 

I am wondering if my approach makes sense and/or if there is a way to overcome the described problem.

**Comment by dzello** [comment]
The relative path to the custom theme may need to be different for presentations that are nested in sections.

Can you share the front matter where you're setting up the custom theme?

**Comment by ccamara** [comment]
Sure! Here it is:

```toml
+++
title = "My awesome title"
description = ""
outputs = ["Reveal"]


[reveal_hugo]
custom_theme = "my-custom-theme.scss"
custom_theme_compile = true
plugins = ["plugin/gallery/gallery.plugin.js"]

+++
```
