### ISSUE TITLE
Duplicate images in public folder

### ISSUE THREAD

**Issue by ccamara** [dzello/reveal-hugo#43]
While debugging #41, I noted that some images are duplicated in `public` folder after being processed by `hugo` command.

This is my current setup:

`config.toml`:

```toml

baseURL = "/"
languageCode = "en-us"
title = "My slides"

theme = "reveal-hugo"

relativeURLs = true
uglyURLs = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
```

I am using page bundles for storing images, making my typical page structure as follows:  `/content/my-slide/img`

When processed by `hugo` command, those images are duplicated, in `public/img` folder + `public/my-slide/img` folder. I am wondering what happens if I have two different images with same name in two folders.
