### ISSUE TITLE
Please add examples of how to set text foreground and background colors...

### ISSUE THREAD

**Issue by dankegel** [dzello/reveal-hugo#6]
I know, it shouldn't need an example, but for some reason it's not working here.

**Comment by dzello** [comment]
Thanks for opening the issue. Reveal.js doesn't have a great way to change colors other than creating a new theme and pointing to it (which isn't hard but does take a little time). The alternative is adding CSS to the page that overrides the styles from a Reveal.js theme.

For simple cases that'd be my recommendation, and based on that I've added a new feature to reveal-hugo that makes it easier to get custom CSS on the page on a global or per-presentation basis. Have a look at [slides 15-17](https://reveal-hugo.dzello.com/#/15) where layout extension is documented. Essentially, you can create a partial with HTML that will be injected into the page of your presentation. In there you can put a style tag with your CSS customizations.

As far as what CSS to put, I had a very quick look at where color is specified in a Reveal.js CSS theme file. These are the majority of the selectors, set to some colors I made up:

```css
.reveal {
  color: #FFDC00;
}

::selection {
  color: #FFDC00;
  background: #7FDBFF;
}

::-moz-selection {
  color: #FFDC00;
  background: #7FDBFF;
}

section.has-dark-background, section.has-dark-background h1, section.has-dark-background h2, section.has-dark-background h3, section.has-dark-background h4, section.has-dark-background h5, section.has-dark-background h6 {
  color: #FFDC00;
}

section.has-light-background, section.has-light-background h1, section.has-light-background h2, section.has-light-background h3, section.has-light-background h4, section.has-light-background h5, section.has-light-background h6 {
  color: #85144b;
}

.reveal a {
  color: #7FDBFF;
}

.reveal a:hover {
  color: #7FDBFF;
}

.reveal blockquote {
  background: rgba(255, 255, 255, 0.05);
}

.reveal section img {
  background: rgba(255, 255, 255, 0.12);
  border: 4px solid #FFDC00;
}

.reveal a:hover img {
  background: rgba(255, 255, 255, 0.2);
  border-color: #7FDBFF;
}

.reveal .roll span:after {
  color: #FFDC00;
  background: #7FDBFF;
}

.reveal .controls {
  color: #7FDBFF;
}

.reveal .progress {
  background: rgba(0, 0, 0, 0.2);
  color: #7FDBFF;
}

@media print {
  .backgrounds {
    background-color: #85144b;
  }
}
```

If you add those styles to a `reveal-hugo/head.html` partial (or presentation-specific one) and change the colors to the ones that you want, you should have it looking about right.
